
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: Williamphoenix@etztec.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "test.freelancers.com"
      dns01:
        cloudflare:
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: batman@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - ""
      dns01:
        cloudflare:
          email: william.phoenix@etztec.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
          email: william.phoneix@etztec.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
