apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-helm-chart-value-overrides
  namespace: cert-manager
data:
  values.yaml: |-
    # paste chart values.yaml (indented) here and alter as required>
